[package]
name = "cinder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mira = "0.1.13"
const-cstr = "0.3.0"
winit = "0.26.1"
lazy_static = "1.4.0"
paste = "1.0.6"