/// Structure type for Vulkan Structs
#[derive(Clone, Copy, Debug)]
pub enum StructureType {
    Unknown,
    ApplicationInfo,
    InstanceCreateInfo,
    DeviceQueueCreateInfo,
    DeviceCreateInfo,
    SubmitInfo,
    MemoryAllocateInfo,
    MappedMemoryRange,
    BindSparseInfo,
    FenceCreateInfo,
    SemaphoreCreateInfo,
    EventCreateInfo,
    QueryPoolCreateInfo,
    BufferCreateInfo,
    BufferViewCreateInfo,
    ImageCreateInfo,
    ImageViewCreateInfo,
    ShaderModuleCreateInfo,
    PipelineCacheCreateInfo,
    PipelineShaderStageCreateInfo,
    PipelineVertexInputStateCreateInfo,
    PipelineInputAssemblyStateCreateInfo,
    PipelineTessellationStateCreateInfo,
    PipelineViewportStateCreateInfo,
    PipelineRasterizationStateCreateInfo,
    PipelineMultisampleStateCreateInfo,
    PipelineDepthStencilStateCreateInfo,
    PipelineColorBlendStateCreateInfo,
    PipelineDynamicStateCreateInfo,
    GraphicsPipelineCreateInfo,
    ComputePipelineCreateInfo,
    PipelineLayoutCreateInfo,
    SamplerCreateInfo,
    DescriptorSetLayoutCreateInfo,
    DescriptorPoolCreateInfo,
    DescriptorSetAllocateInfo,
    WriteDescriptorSet,
    CopyDescriptorSet,
    FramebufferCreateInfo,
    RenderPassCreateInfo,
    CommandPoolCreateInfo,
    CommandBufferAllocateInfo,
    CommandBufferInheritanceInfo,
    CommandBufferBeginInfo,
    RenderPassBeginInfo,
    BufferMemoryBarrier,
    ImageMemoryBarrier,
    MemoryBarrier,
    LoaderInstanceCreateInfo,
    LoaderDeviceCreateInfo,
    PhysicalDeviceSubgroupProperties,
    BindBufferMemoryInfo,
    BindImageMemoryInfo,
    PhysicalDevice16BitStorageFeatures,
    MemoryDedicatedRequirements,
    MemoryDedicatedAllocateInfo,
    MemoryAllocateFlagsInfo,
    DeviceGroupRenderPassBeginInfo,
    DeviceGroupCommandBufferBeginInfo,
    DeviceGroupSubmitInfo,
    DeviceGroupBindSparseInfo,
    BindBufferMemoryDeviceGroupInfo,
    BindImageMemoryDeviceGroupInfo,
    PhysicalDeviceGroupProperties,
    DeviceGroupDeviceCreateInfo,
    BufferMemoryRequirementsInfo2,
    ImageMemoryRequirementsInfo2,
    ImageSparseMemoryRequirementsInfo2,
    MemoryRequirements2,
    SparseImageMemoryRequirements2,
    PhysicalDeviceFeatures2,
    PhysicalDeviceProperties2,
    FormatProperties2,
    ImageFormatProperties2,
    PhysicalDeviceImageFormatInfo2,
    QueueFamilyProperties2,
    PhysicalDeviceMemoryProperties2,
    SparseImageFormatProperties2,
    PhysicalDeviceSparseImageFormatInfo2,
    PhysicalDevicePointClippingProperties,
    RenderPassInputAttachmentAspectCreateInfo,
    ImageViewUsageCreateInfo,
    PipelineTessellationDomainOriginStateCreateInfo,
    RenderPassMultiviewCreateInfo,
    PhysicalDeviceMultiviewFeatures,
    PhysicalDeviceMultiviewProperties,
    PhysicalDeviceVariablePointersFeatures,
    ProtectedSubmitInfo,
    PhysicalDeviceProtectedMemoryFeatures,
    PhysicalDeviceProtectedMemoryProperties,
    DeviceQueueInfo2,
    SamplerYcbcrConversionCreateInfo,
    SamplerYcbcrConversionInfo,
    BindImagePlaneMemoryInfo,
    ImagePlaneMemoryRequirementsInfo,
    PhysicalDeviceSamplerYcbcrConversionFeatures,
    SamplerYcbcrConversionImageFormatProperties,
    DescriptorUpdateTemplateCreateInfo,
    PhysicalDeviceExternalImageFormatInfo,
    ExternalImageFormatProperties,
    PhysicalDeviceExternalBufferInfo,
    ExternalBufferProperties,
    PhysicalDeviceIdProperties,
    ExternalMemoryBufferCreateInfo,
    ExternalMemoryImageCreateInfo,
    ExportMemoryAllocateInfo,
    PhysicalDeviceExternalFenceInfo,
    ExternalFenceProperties,
    ExportFenceCreateInfo,
    ExportSemaphoreCreateInfo,
    PhysicalDeviceExternalSemaphoreInfo,
    ExternalSemaphoreProperties,
    PhysicalDeviceMaintenance3Properties,
    DescriptorSetLayoutSupport,
    PhysicalDeviceShaderDrawParametersFeatures,
    PhysicalDeviceVulkan11Features,
    PhysicalDeviceVulkan11Properties,
    PhysicalDeviceVulkan12Features,
    PhysicalDeviceVulkan12Properties,
    ImageFormatListCreateInfo,
    AttachmentDescription2,
    AttachmentReference2,
    SubpassDescription2,
    SubpassDependency2,
    RenderPassCreateInfo2,
    SubpassBeginInfo,
    SubpassEndInfo,
    PhysicalDevice8BitStorageFeatures,
    PhysicalDeviceDriverProperties,
    PhysicalDeviceShaderAtomicInt64Features,
    PhysicalDeviceShaderFloat16Int8Features,
    PhysicalDeviceFloatControlsProperties,
    DescriptorSetLayoutBindingFlagsCreateInfo,
    PhysicalDeviceDescriptorIndexingFeatures,
    PhysicalDeviceDescriptorIndexingProperties,
    DescriptorSetVariableDescriptorCountAllocateInfo,
    DescriptorSetVariableDescriptorCountLayoutSupport,
    PhysicalDeviceDepthStencilResolveProperties,
    SubpassDescriptionDepthStencilResolve,
    PhysicalDeviceScalarBlockLayoutFeatures,
    ImageStencilUsageCreateInfo,
    PhysicalDeviceSamplerFilterMinmaxProperties,
    SamplerReductionModeCreateInfo,
    PhysicalDeviceVulkanMemoryModelFeatures,
    PhysicalDeviceImagelessFramebufferFeatures,
    FramebufferAttachmentsCreateInfo,
    FramebufferAttachmentImageInfo,
    RenderPassAttachmentBeginInfo,
    PhysicalDeviceUniformBufferStandardLayoutFeatures,
    PhysicalDeviceShaderSubgroupExtendedTypesFeatures,
    PhysicalDeviceSeparateDepthStencilLayoutsFeatures,
    AttachmentReferenceStencilLayout,
    AttachmentDescriptionStencilLayout,
    PhysicalDeviceHostQueryResetFeatures,
    PhysicalDeviceTimelineSemaphoreFeatures,
    PhysicalDeviceTimelineSemaphoreProperties,
    SemaphoreTypeCreateInfo,
    TimelineSemaphoreSubmitInfo,
    SemaphoreWaitInfo,
    SemaphoreSignalInfo,
    PhysicalDeviceBufferDeviceAddressFeatures,
    BufferDeviceAddressInfo,
    BufferOpaqueCaptureAddressCreateInfo,
    MemoryOpaqueCaptureAddressAllocateInfo,
    DeviceMemoryOpaqueCaptureAddressInfo,
    PhysicalDeviceVulkan13Features,
    PhysicalDeviceVulkan13Properties,
    PipelineCreationFeedbackCreateInfo,
    PhysicalDeviceShaderTerminateInvocationFeatures,
    PhysicalDeviceToolProperties,
    PhysicalDeviceShaderDemoteToHelperInvocationFeatures,
    PhysicalDevicePrivateDataFeatures,
    DevicePrivateDataCreateInfo,
    PrivateDataSlotCreateInfo,
    PhysicalDevicePipelineCreationCacheControlFeatures,
    MemoryBarrier2,
    BufferMemoryBarrier2,
    ImageMemoryBarrier2,
    DependencyInfo,
    SubmitInfo2,
    SemaphoreSubmitInfo,
    CommandBufferSubmitInfo,
    PhysicalDeviceSynchronization2Features,
    PhysicalDeviceZeroInitializeWorkgroupMemoryFeatures,
    PhysicalDeviceImageRobustnessFeatures,
    CopyBufferInfo2,
    CopyImageInfo2,
    CopyBufferToImageInfo2,
    CopyImageToBufferInfo2,
    BlitImageInfo2,
    ResolveImageInfo2,
    BufferCopy2,
    ImageCopy2,
    ImageBlit2,
    BufferImageCopy2,
    ImageResolve2,
    PhysicalDeviceSubgroupSizeControlProperties,
    PipelineShaderStageRequiredSubgroupSizeCreateInfo,
    PhysicalDeviceSubgroupSizeControlFeatures,
    PhysicalDeviceInlineUniformBlockFeatures,
    PhysicalDeviceInlineUniformBlockProperties,
    WriteDescriptorSetInlineUniformBlock,
    DescriptorPoolInlineUniformBlockCreateInfo,
    PhysicalDeviceTextureCompressionAstcHdrFeatures,
    RenderingInfo,
    RenderingAttachmentInfo,
    PipelineRenderingCreateInfo,
    PhysicalDeviceDynamicRenderingFeatures,
    CommandBufferInheritanceRenderingInfo,
    PhysicalDeviceShaderIntegerDotProductFeatures,
    PhysicalDeviceShaderIntegerDotProductProperties,
    PhysicalDeviceTexelBufferAlignmentProperties,
    FormatProperties3,
    PhysicalDeviceMaintenance4Features,
    PhysicalDeviceMaintenance4Properties,
    DeviceBufferMemoryRequirements,
    DeviceImageMemoryRequirements,
    SwapchainCreateInfoKhr,
    PresentInfoKhr,
    DeviceGroupPresentCapabilitiesKhr,
    ImageSwapchainCreateInfoKhr,
    BindImageMemorySwapchainInfoKhr,
    AcquireNextImageInfoKhr,
    DeviceGroupPresentInfoKhr,
    DeviceGroupSwapchainCreateInfoKhr,
    DisplayModeCreateInfoKhr,
    DisplaySurfaceCreateInfoKhr,
    DisplayPresentInfoKhr,
    XlibSurfaceCreateInfoKhr,
    XcbSurfaceCreateInfoKhr,
    WaylandSurfaceCreateInfoKhr,
    AndroidSurfaceCreateInfoKhr,
    Win32SurfaceCreateInfoKhr,
    DebugReportCallbackCreateInfoExt,
    PipelineRasterizationStateRasterizationOrderAmd,
    DebugMarkerObjectNameInfoExt,
    DebugMarkerObjectTagInfoExt,
    DebugMarkerMarkerInfoExt,
    VkEnableBetaExtensionsvideoProfileKhr,
    VkEnableBetaExtensionsvideoCapabilitiesKhr,
    VkEnableBetaExtensionsvideoPictureResourceKhr,
    VkEnableBetaExtensionsvideoGetMemoryPropertiesKhr,
    VkEnableBetaExtensionsvideoBindMemoryKhr,
    VkEnableBetaExtensionsvideoSessionCreateInfoKhr,
    VkEnableBetaExtensionsvideoSessionParametersCreateInfoKhr,
    VkEnableBetaExtensionsvideoSessionParametersUpdateInfoKhr,
    VkEnableBetaExtensionsvideoBeginCodingInfoKhr,
    VkEnableBetaExtensionsvideoEndCodingInfoKhr,
    VkEnableBetaExtensionsvideoCodingControlInfoKhr,
    VkEnableBetaExtensionsvideoReferenceSlotKhr,
    VkEnableBetaExtensionsvideoQueueFamilyProperties2Khr,
    VkEnableBetaExtensionsvideoProfilesKhr,
    VkEnableBetaExtensionsphysicalDeviceVideoFormatInfoKhr,
    VkEnableBetaExtensionsvideoFormatPropertiesKhr,
    VkEnableBetaExtensionsqueueFamilyQueryResultStatusProperties2Khr,
    VkEnableBetaExtensionsvideoDecodeInfoKhr,
    VkEnableBetaExtensionsvideoDecodeCapabilitiesKhr,
    DedicatedAllocationImageCreateInfoNv,
    DedicatedAllocationBufferCreateInfoNv,
    DedicatedAllocationMemoryAllocateInfoNv,
    PhysicalDeviceTransformFeedbackFeaturesExt,
    PhysicalDeviceTransformFeedbackPropertiesExt,
    PipelineRasterizationStateStreamCreateInfoExt,
    CuModuleCreateInfoNvx,
    CuFunctionCreateInfoNvx,
    CuLaunchInfoNvx,
    ImageViewHandleInfoNvx,
    ImageViewAddressPropertiesNvx,
    VkEnableBetaExtensionsvideoEncodeH264CapabilitiesExt,
    VkEnableBetaExtensionsvideoEncodeH264SessionParametersCreateInfoExt,
    VkEnableBetaExtensionsvideoEncodeH264SessionParametersAddInfoExt,
    VkEnableBetaExtensionsvideoEncodeH264VclFrameInfoExt,
    VkEnableBetaExtensionsvideoEncodeH264DpbSlotInfoExt,
    VkEnableBetaExtensionsvideoEncodeH264NaluSliceExt,
    VkEnableBetaExtensionsvideoEncodeH264EmitPictureParametersExt,
    VkEnableBetaExtensionsvideoEncodeH264ProfileExt,
    VkEnableBetaExtensionsvideoEncodeH264RateControlInfoExt,
    VkEnableBetaExtensionsvideoEncodeH264RateControlLayerInfoExt,
    VkEnableBetaExtensionsvideoEncodeH264ReferenceListsExt,
    VkEnableBetaExtensionsvideoEncodeH265CapabilitiesExt,
    VkEnableBetaExtensionsvideoEncodeH265SessionParametersCreateInfoExt,
    VkEnableBetaExtensionsvideoEncodeH265SessionParametersAddInfoExt,
    VkEnableBetaExtensionsvideoEncodeH265VclFrameInfoExt,
    VkEnableBetaExtensionsvideoEncodeH265DpbSlotInfoExt,
    VkEnableBetaExtensionsvideoEncodeH265NaluSliceSegmentExt,
    VkEnableBetaExtensionsvideoEncodeH265EmitPictureParametersExt,
    VkEnableBetaExtensionsvideoEncodeH265ProfileExt,
    VkEnableBetaExtensionsvideoEncodeH265ReferenceListsExt,
    VkEnableBetaExtensionsvideoEncodeH265RateControlInfoExt,
    VkEnableBetaExtensionsvideoEncodeH265RateControlLayerInfoExt,
    VkEnableBetaExtensionsvideoDecodeH264CapabilitiesExt,
    VkEnableBetaExtensionsvideoDecodeH264PictureInfoExt,
    VkEnableBetaExtensionsvideoDecodeH264MvcExt,
    VkEnableBetaExtensionsvideoDecodeH264ProfileExt,
    VkEnableBetaExtensionsvideoDecodeH264SessionParametersCreateInfoExt,
    VkEnableBetaExtensionsvideoDecodeH264SessionParametersAddInfoExt,
    VkEnableBetaExtensionsvideoDecodeH264DpbSlotInfoExt,
    TextureLodGatherFormatPropertiesAmd,
    RenderingFragmentShadingRateAttachmentInfoKhr,
    RenderingFragmentDensityMapAttachmentInfoExt,
    AttachmentSampleCountInfoAmd,
    MultiviewPerViewAttributesInfoNvx,
    StreamDescriptorSurfaceCreateInfoGgp,
    PhysicalDeviceCornerSampledImageFeaturesNv,
    ExternalMemoryImageCreateInfoNv,
    ExportMemoryAllocateInfoNv,
    ImportMemoryWin32HandleInfoNv,
    ExportMemoryWin32HandleInfoNv,
    Win32KeyedMutexAcquireReleaseInfoNv,
    ValidationFlagsExt,
    ViSurfaceCreateInfoNn,
    ImageViewAstcDecodeModeExt,
    PhysicalDeviceAstcDecodeFeaturesExt,
    ImportMemoryWin32HandleInfoKhr,
    ExportMemoryWin32HandleInfoKhr,
    MemoryWin32HandlePropertiesKhr,
    MemoryGetWin32HandleInfoKhr,
    ImportMemoryFdInfoKhr,
    MemoryFdPropertiesKhr,
    MemoryGetFdInfoKhr,
    Win32KeyedMutexAcquireReleaseInfoKhr,
    ImportSemaphoreWin32HandleInfoKhr,
    ExportSemaphoreWin32HandleInfoKhr,
    D3D12FenceSubmitInfoKhr,
    SemaphoreGetWin32HandleInfoKhr,
    ImportSemaphoreFdInfoKhr,
    SemaphoreGetFdInfoKhr,
    PhysicalDevicePushDescriptorPropertiesKhr,
    CommandBufferInheritanceConditionalRenderingInfoExt,
    PhysicalDeviceConditionalRenderingFeaturesExt,
    ConditionalRenderingBeginInfoExt,
    PresentRegionsKhr,
    PipelineViewportWScalingStateCreateInfoNv,
    SurfaceCapabilities2Ext,
    DisplayPowerInfoExt,
    DeviceEventInfoExt,
    DisplayEventInfoExt,
    SwapchainCounterCreateInfoExt,
    PresentTimesInfoGoogle,
    PhysicalDeviceMultiviewPerViewAttributesPropertiesNvx,
    PipelineViewportSwizzleStateCreateInfoNv,
    PhysicalDeviceDiscardRectanglePropertiesExt,
    PipelineDiscardRectangleStateCreateInfoExt,
    PhysicalDeviceConservativeRasterizationPropertiesExt,
    PipelineRasterizationConservativeStateCreateInfoExt,
    PhysicalDeviceDepthClipEnableFeaturesExt,
    PipelineRasterizationDepthClipStateCreateInfoExt,
    HdrMetadataExt,
    SharedPresentSurfaceCapabilitiesKhr,
    ImportFenceWin32HandleInfoKhr,
    ExportFenceWin32HandleInfoKhr,
    FenceGetWin32HandleInfoKhr,
    ImportFenceFdInfoKhr,
    FenceGetFdInfoKhr,
    PhysicalDevicePerformanceQueryFeaturesKhr,
    PhysicalDevicePerformanceQueryPropertiesKhr,
    QueryPoolPerformanceCreateInfoKhr,
    PerformanceQuerySubmitInfoKhr,
    AcquireProfilingLockInfoKhr,
    PerformanceCounterKhr,
    PerformanceCounterDescriptionKhr,
    PhysicalDeviceSurfaceInfo2Khr,
    SurfaceCapabilities2Khr,
    SurfaceFormat2Khr,
    DisplayProperties2Khr,
    DisplayPlaneProperties2Khr,
    DisplayModeProperties2Khr,
    DisplayPlaneInfo2Khr,
    DisplayPlaneCapabilities2Khr,
    IosSurfaceCreateInfoMvk,
    MacosSurfaceCreateInfoMvk,
    DebugUtilsObjectNameInfoExt,
    DebugUtilsObjectTagInfoExt,
    DebugUtilsLabelExt,
    DebugUtilsMessengerCallbackDataExt,
    DebugUtilsMessengerCreateInfoExt,
    AndroidHardwareBufferUsageAndroid,
    AndroidHardwareBufferPropertiesAndroid,
    AndroidHardwareBufferFormatPropertiesAndroid,
    ImportAndroidHardwareBufferInfoAndroid,
    MemoryGetAndroidHardwareBufferInfoAndroid,
    ExternalFormatAndroid,
    AndroidHardwareBufferFormatProperties2Android,
    SampleLocationsInfoExt,
    RenderPassSampleLocationsBeginInfoExt,
    PipelineSampleLocationsStateCreateInfoExt,
    PhysicalDeviceSampleLocationsPropertiesExt,
    MultisamplePropertiesExt,
    PhysicalDeviceBlendOperationAdvancedFeaturesExt,
    PhysicalDeviceBlendOperationAdvancedPropertiesExt,
    PipelineColorBlendAdvancedStateCreateInfoExt,
    PipelineCoverageToColorStateCreateInfoNv,
    WriteDescriptorSetAccelerationStructureKhr,
    AccelerationStructureBuildGeometryInfoKhr,
    AccelerationStructureDeviceAddressInfoKhr,
    AccelerationStructureGeometryAabbsDataKhr,
    AccelerationStructureGeometryInstancesDataKhr,
    AccelerationStructureGeometryTrianglesDataKhr,
    AccelerationStructureGeometryKhr,
    AccelerationStructureVersionInfoKhr,
    CopyAccelerationStructureInfoKhr,
    CopyAccelerationStructureToMemoryInfoKhr,
    CopyMemoryToAccelerationStructureInfoKhr,
    PhysicalDeviceAccelerationStructureFeaturesKhr,
    PhysicalDeviceAccelerationStructurePropertiesKhr,
    AccelerationStructureCreateInfoKhr,
    AccelerationStructureBuildSizesInfoKhr,
    PhysicalDeviceRayTracingPipelineFeaturesKhr,
    PhysicalDeviceRayTracingPipelinePropertiesKhr,
    RayTracingPipelineCreateInfoKhr,
    RayTracingShaderGroupCreateInfoKhr,
    RayTracingPipelineInterfaceCreateInfoKhr,
    PhysicalDeviceRayQueryFeaturesKhr,
    PipelineCoverageModulationStateCreateInfoNv,
    PhysicalDeviceShaderSmBuiltinsFeaturesNv,
    PhysicalDeviceShaderSmBuiltinsPropertiesNv,
    DrmFormatModifierPropertiesListExt,
    PhysicalDeviceImageDrmFormatModifierInfoExt,
    ImageDrmFormatModifierListCreateInfoExt,
    ImageDrmFormatModifierExplicitCreateInfoExt,
    ImageDrmFormatModifierPropertiesExt,
    DrmFormatModifierPropertiesList2Ext,
    ValidationCacheCreateInfoExt,
    ShaderModuleValidationCacheCreateInfoExt,
    VkEnableBetaExtensionsphysicalDevicePortabilitySubsetFeaturesKhr,
    VkEnableBetaExtensionsphysicalDevicePortabilitySubsetPropertiesKhr,
    PipelineViewportShadingRateImageStateCreateInfoNv,
    PhysicalDeviceShadingRateImageFeaturesNv,
    PhysicalDeviceShadingRateImagePropertiesNv,
    PipelineViewportCoarseSampleOrderStateCreateInfoNv,
    RayTracingPipelineCreateInfoNv,
    AccelerationStructureCreateInfoNv,
    GeometryNv,
    GeometryTrianglesNv,
    GeometryAabbNv,
    BindAccelerationStructureMemoryInfoNv,
    WriteDescriptorSetAccelerationStructureNv,
    AccelerationStructureMemoryRequirementsInfoNv,
    PhysicalDeviceRayTracingPropertiesNv,
    RayTracingShaderGroupCreateInfoNv,
    AccelerationStructureInfoNv,
    PhysicalDeviceRepresentativeFragmentTestFeaturesNv,
    PipelineRepresentativeFragmentTestStateCreateInfoNv,
    PhysicalDeviceImageViewImageFormatInfoExt,
    FilterCubicImageViewImageFormatPropertiesExt,
    ImportMemoryHostPointerInfoExt,
    MemoryHostPointerPropertiesExt,
    PhysicalDeviceExternalMemoryHostPropertiesExt,
    PhysicalDeviceShaderClockFeaturesKhr,
    PipelineCompilerControlCreateInfoAmd,
    CalibratedTimestampInfoExt,
    PhysicalDeviceShaderCorePropertiesAmd,
    VkEnableBetaExtensionsvideoDecodeH265CapabilitiesExt,
    VkEnableBetaExtensionsvideoDecodeH265SessionParametersCreateInfoExt,
    VkEnableBetaExtensionsvideoDecodeH265SessionParametersAddInfoExt,
    VkEnableBetaExtensionsvideoDecodeH265ProfileExt,
    VkEnableBetaExtensionsvideoDecodeH265PictureInfoExt,
    VkEnableBetaExtensionsvideoDecodeH265DpbSlotInfoExt,
    DeviceQueueGlobalPriorityCreateInfoKhr,
    PhysicalDeviceGlobalPriorityQueryFeaturesKhr,
    QueueFamilyGlobalPriorityPropertiesKhr,
    DeviceMemoryOverallocationCreateInfoAmd,
    PhysicalDeviceVertexAttributeDivisorPropertiesExt,
    PipelineVertexInputDivisorStateCreateInfoExt,
    PhysicalDeviceVertexAttributeDivisorFeaturesExt,
    PresentFrameTokenGgp,
    PhysicalDeviceComputeShaderDerivativesFeaturesNv,
    PhysicalDeviceMeshShaderFeaturesNv,
    PhysicalDeviceMeshShaderPropertiesNv,
    PhysicalDeviceFragmentShaderBarycentricFeaturesNv,
    PhysicalDeviceShaderImageFootprintFeaturesNv,
    PipelineViewportExclusiveScissorStateCreateInfoNv,
    PhysicalDeviceExclusiveScissorFeaturesNv,
    CheckpointDataNv,
    QueueFamilyCheckpointPropertiesNv,
    PhysicalDeviceShaderIntegerFunctions2FeaturesIntel,
    QueryPoolPerformanceQueryCreateInfoIntel,
    InitializePerformanceApiInfoIntel,
    PerformanceMarkerInfoIntel,
    PerformanceStreamMarkerInfoIntel,
    PerformanceOverrideInfoIntel,
    PerformanceConfigurationAcquireInfoIntel,
    PhysicalDevicePciBusInfoPropertiesExt,
    DisplayNativeHdrSurfaceCapabilitiesAmd,
    SwapchainDisplayNativeHdrCreateInfoAmd,
    ImagepipeSurfaceCreateInfoFuchsia,
    MetalSurfaceCreateInfoExt,
    PhysicalDeviceFragmentDensityMapFeaturesExt,
    PhysicalDeviceFragmentDensityMapPropertiesExt,
    RenderPassFragmentDensityMapCreateInfoExt,
    FragmentShadingRateAttachmentInfoKhr,
    PipelineFragmentShadingRateStateCreateInfoKhr,
    PhysicalDeviceFragmentShadingRatePropertiesKhr,
    PhysicalDeviceFragmentShadingRateFeaturesKhr,
    PhysicalDeviceFragmentShadingRateKhr,
    PhysicalDeviceShaderCoreProperties2Amd,
    PhysicalDeviceCoherentMemoryFeaturesAmd,
    PhysicalDeviceShaderImageAtomicInt64FeaturesExt,
    PhysicalDeviceMemoryBudgetPropertiesExt,
    PhysicalDeviceMemoryPriorityFeaturesExt,
    MemoryPriorityAllocateInfoExt,
    SurfaceProtectedCapabilitiesKhr,
    PhysicalDeviceDedicatedAllocationImageAliasingFeaturesNv,
    PhysicalDeviceBufferDeviceAddressFeaturesExt,
    BufferDeviceAddressCreateInfoExt,
    ValidationFeaturesExt,
    PhysicalDevicePresentWaitFeaturesKhr,
    PhysicalDeviceCooperativeMatrixFeaturesNv,
    CooperativeMatrixPropertiesNv,
    PhysicalDeviceCooperativeMatrixPropertiesNv,
    PhysicalDeviceCoverageReductionModeFeaturesNv,
    PipelineCoverageReductionStateCreateInfoNv,
    FramebufferMixedSamplesCombinationNv,
    PhysicalDeviceFragmentShaderInterlockFeaturesExt,
    PhysicalDeviceYcbcrImageArraysFeaturesExt,
    PhysicalDeviceProvokingVertexFeaturesExt,
    PipelineRasterizationProvokingVertexStateCreateInfoExt,
    PhysicalDeviceProvokingVertexPropertiesExt,
    SurfaceFullScreenExclusiveInfoExt,
    SurfaceCapabilitiesFullScreenExclusiveExt,
    SurfaceFullScreenExclusiveWin32InfoExt,
    HeadlessSurfaceCreateInfoExt,
    PhysicalDeviceLineRasterizationFeaturesExt,
    PipelineRasterizationLineStateCreateInfoExt,
    PhysicalDeviceLineRasterizationPropertiesExt,
    PhysicalDeviceShaderAtomicFloatFeaturesExt,
    PhysicalDeviceIndexTypeUint8FeaturesExt,
    PhysicalDeviceExtendedDynamicStateFeaturesExt,
    PhysicalDevicePipelineExecutablePropertiesFeaturesKhr,
    PipelineInfoKhr,
    PipelineExecutablePropertiesKhr,
    PipelineExecutableInfoKhr,
    PipelineExecutableStatisticKhr,
    PipelineExecutableInternalRepresentationKhr,
    PhysicalDeviceShaderAtomicFloat2FeaturesExt,
    PhysicalDeviceDeviceGeneratedCommandsPropertiesNv,
    GraphicsShaderGroupCreateInfoNv,
    GraphicsPipelineShaderGroupsCreateInfoNv,
    IndirectCommandsLayoutTokenNv,
    IndirectCommandsLayoutCreateInfoNv,
    GeneratedCommandsInfoNv,
    GeneratedCommandsMemoryRequirementsInfoNv,
    PhysicalDeviceDeviceGeneratedCommandsFeaturesNv,
    PhysicalDeviceInheritedViewportScissorFeaturesNv,
    CommandBufferInheritanceViewportScissorInfoNv,
    PhysicalDeviceTexelBufferAlignmentFeaturesExt,
    CommandBufferInheritanceRenderPassTransformInfoQcom,
    RenderPassTransformBeginInfoQcom,
    PhysicalDeviceDeviceMemoryReportFeaturesExt,
    DeviceDeviceMemoryReportCreateInfoExt,
    DeviceMemoryReportCallbackDataExt,
    PhysicalDeviceRobustness2FeaturesExt,
    PhysicalDeviceRobustness2PropertiesExt,
    SamplerCustomBorderColorCreateInfoExt,
    PhysicalDeviceCustomBorderColorPropertiesExt,
    PhysicalDeviceCustomBorderColorFeaturesExt,
    PipelineLibraryCreateInfoKhr,
    PresentIdKhr,
    PhysicalDevicePresentIdFeaturesKhr,
    VkEnableBetaExtensionsvideoEncodeInfoKhr,
    VkEnableBetaExtensionsvideoEncodeRateControlInfoKhr,
    VkEnableBetaExtensionsvideoEncodeRateControlLayerInfoKhr,
    VkEnableBetaExtensionsvideoEncodeCapabilitiesKhr,
    PhysicalDeviceDiagnosticsConfigFeaturesNv,
    DeviceDiagnosticsConfigCreateInfoNv,
    QueueFamilyCheckpointProperties2Nv,
    CheckpointData2Nv,
    PhysicalDeviceGraphicsPipelineLibraryFeaturesExt,
    PhysicalDeviceGraphicsPipelineLibraryPropertiesExt,
    GraphicsPipelineLibraryCreateInfoExt,
    PhysicalDeviceShaderSubgroupUniformControlFlowFeaturesKhr,
    PhysicalDeviceFragmentShadingRateEnumsPropertiesNv,
    PhysicalDeviceFragmentShadingRateEnumsFeaturesNv,
    PipelineFragmentShadingRateEnumStateCreateInfoNv,
    AccelerationStructureGeometryMotionTrianglesDataNv,
    PhysicalDeviceRayTracingMotionBlurFeaturesNv,
    AccelerationStructureMotionInfoNv,
    PhysicalDeviceYcbcr2Plane444FormatsFeaturesExt,
    PhysicalDeviceFragmentDensityMap2FeaturesExt,
    PhysicalDeviceFragmentDensityMap2PropertiesExt,
    CopyCommandTransformInfoQcom,
    PhysicalDeviceWorkgroupMemoryExplicitLayoutFeaturesKhr,
    PhysicalDevice4444FormatsFeaturesExt,
    PhysicalDeviceRasterizationOrderAttachmentAccessFeaturesArm,
    PhysicalDeviceRgba10X6FormatsFeaturesExt,
    DirectfbSurfaceCreateInfoExt,
    PhysicalDeviceMutableDescriptorTypeFeaturesValve,
    MutableDescriptorTypeCreateInfoValve,
    PhysicalDeviceVertexInputDynamicStateFeaturesExt,
    VertexInputBindingDescription2Ext,
    VertexInputAttributeDescription2Ext,
    PhysicalDeviceDrmPropertiesExt,
    PhysicalDeviceDepthClipControlFeaturesExt,
    PipelineViewportDepthClipControlCreateInfoExt,
    PhysicalDevicePrimitiveTopologyListRestartFeaturesExt,
    ImportMemoryZirconHandleInfoFuchsia,
    MemoryZirconHandlePropertiesFuchsia,
    MemoryGetZirconHandleInfoFuchsia,
    ImportSemaphoreZirconHandleInfoFuchsia,
    SemaphoreGetZirconHandleInfoFuchsia,
    BufferCollectionCreateInfoFuchsia,
    ImportMemoryBufferCollectionFuchsia,
    BufferCollectionImageCreateInfoFuchsia,
    BufferCollectionPropertiesFuchsia,
    BufferConstraintsInfoFuchsia,
    BufferCollectionBufferCreateInfoFuchsia,
    ImageConstraintsInfoFuchsia,
    ImageFormatConstraintsInfoFuchsia,
    SysmemColorSpaceFuchsia,
    BufferCollectionConstraintsInfoFuchsia,
    SubpassShadingPipelineCreateInfoHuawei,
    PhysicalDeviceSubpassShadingFeaturesHuawei,
    PhysicalDeviceSubpassShadingPropertiesHuawei,
    PhysicalDeviceInvocationMaskFeaturesHuawei,
    MemoryGetRemoteAddressInfoNv,
    PhysicalDeviceExternalMemoryRdmaFeaturesNv,
    PhysicalDeviceExtendedDynamicState2FeaturesExt,
    ScreenSurfaceCreateInfoQnx,
    PhysicalDeviceColorWriteEnableFeaturesExt,
    PipelineColorWriteCreateInfoExt,
    PhysicalDevicePrimitivesGeneratedQueryFeaturesExt,
    PhysicalDeviceImageViewMinLodFeaturesExt,
    ImageViewMinLodCreateInfoExt,
    PhysicalDeviceMultiDrawFeaturesExt,
    PhysicalDeviceMultiDrawPropertiesExt,
    PhysicalDeviceImage2DViewOf3DFeaturesExt,
    PhysicalDeviceBorderColorSwizzleFeaturesExt,
    SamplerBorderColorComponentMappingCreateInfoExt,
    PhysicalDevicePageableDeviceLocalMemoryFeaturesExt,
    PhysicalDeviceDescriptorSetHostMappingFeaturesValve,
    DescriptorSetBindingReferenceValve,
    DescriptorSetLayoutHostMappingInfoValve,
    PhysicalDeviceFragmentDensityMapOffsetFeaturesQcom,
    PhysicalDeviceFragmentDensityMapOffsetPropertiesQcom,
    SubpassFragmentDensityMapOffsetEndInfoQcom,
    PhysicalDeviceLinearColorAttachmentFeaturesNv,
}

// Check if the From trait works for StructureTypes
#[test]
pub fn from_structure_type_test() {
    let x: StructureType = 10.into();
    println!("{x:?}");
}

/// i32's can go into StructureTypes
impl From<i32> for StructureType {
    fn from(x: i32) -> Self {
        match x {
            0 => StructureType::ApplicationInfo,
            1 => StructureType::InstanceCreateInfo,
            2 => StructureType::DeviceQueueCreateInfo,
            3 => StructureType::DeviceCreateInfo,
            4 => StructureType::SubmitInfo,
            5 => StructureType::MemoryAllocateInfo,
            6 => StructureType::MappedMemoryRange,
            7 => StructureType::BindSparseInfo,
            8 => StructureType::FenceCreateInfo,
            9 => StructureType::SemaphoreCreateInfo,
            10 => StructureType::EventCreateInfo,
            11 => StructureType::QueryPoolCreateInfo,
            12 => StructureType::BufferCreateInfo,
            13 => StructureType::BufferViewCreateInfo,
            14 => StructureType::ImageCreateInfo,
            15 => StructureType::ImageViewCreateInfo,
            16 => StructureType::ShaderModuleCreateInfo,
            17 => StructureType::PipelineCacheCreateInfo,
            18 => StructureType::PipelineShaderStageCreateInfo,
            19 => StructureType::PipelineVertexInputStateCreateInfo,
            20 => StructureType::PipelineInputAssemblyStateCreateInfo,
            21 => StructureType::PipelineTessellationStateCreateInfo,
            22 => StructureType::PipelineViewportStateCreateInfo,
            23 => StructureType::PipelineRasterizationStateCreateInfo,
            24 => StructureType::PipelineMultisampleStateCreateInfo,
            25 => StructureType::PipelineDepthStencilStateCreateInfo,
            26 => StructureType::PipelineColorBlendStateCreateInfo,
            27 => StructureType::PipelineDynamicStateCreateInfo,
            28 => StructureType::GraphicsPipelineCreateInfo,
            29 => StructureType::ComputePipelineCreateInfo,
            30 => StructureType::PipelineLayoutCreateInfo,
            31 => StructureType::SamplerCreateInfo,
            32 => StructureType::DescriptorSetLayoutCreateInfo,
            33 => StructureType::DescriptorPoolCreateInfo,
            34 => StructureType::DescriptorSetAllocateInfo,
            35 => StructureType::WriteDescriptorSet,
            36 => StructureType::CopyDescriptorSet,
            37 => StructureType::FramebufferCreateInfo,
            38 => StructureType::RenderPassCreateInfo,
            39 => StructureType::CommandPoolCreateInfo,
            40 => StructureType::CommandBufferAllocateInfo,
            41 => StructureType::CommandBufferInheritanceInfo,
            42 => StructureType::CommandBufferBeginInfo,
            43 => StructureType::RenderPassBeginInfo,
            44 => StructureType::BufferMemoryBarrier,
            45 => StructureType::ImageMemoryBarrier,
            46 => StructureType::MemoryBarrier,
            47 => StructureType::LoaderInstanceCreateInfo,
            48 => StructureType::LoaderDeviceCreateInfo,
            1000094000 => StructureType::PhysicalDeviceSubgroupProperties,
            1000157000 => StructureType::BindBufferMemoryInfo,
            1000157001 => StructureType::BindImageMemoryInfo,
            1000083000 => StructureType::PhysicalDevice16BitStorageFeatures,
            1000127000 => StructureType::MemoryDedicatedRequirements,
            1000127001 => StructureType::MemoryDedicatedAllocateInfo,
            1000060000 => StructureType::MemoryAllocateFlagsInfo,
            1000060003 => StructureType::DeviceGroupRenderPassBeginInfo,
            1000060004 => StructureType::DeviceGroupCommandBufferBeginInfo,
            1000060005 => StructureType::DeviceGroupSubmitInfo,
            1000060006 => StructureType::DeviceGroupBindSparseInfo,
            1000060013 => StructureType::BindBufferMemoryDeviceGroupInfo,
            1000060014 => StructureType::BindImageMemoryDeviceGroupInfo,
            1000070000 => StructureType::PhysicalDeviceGroupProperties,
            1000070001 => StructureType::DeviceGroupDeviceCreateInfo,
            1000146000 => StructureType::BufferMemoryRequirementsInfo2,
            1000146001 => StructureType::ImageMemoryRequirementsInfo2,
            1000146002 => StructureType::ImageSparseMemoryRequirementsInfo2,
            1000146003 => StructureType::MemoryRequirements2,
            1000146004 => StructureType::SparseImageMemoryRequirements2,
            1000059000 => StructureType::PhysicalDeviceFeatures2,
            1000059001 => StructureType::PhysicalDeviceProperties2,
            1000059002 => StructureType::FormatProperties2,
            1000059003 => StructureType::ImageFormatProperties2,
            1000059004 => StructureType::PhysicalDeviceImageFormatInfo2,
            1000059005 => StructureType::QueueFamilyProperties2,
            1000059006 => StructureType::PhysicalDeviceMemoryProperties2,
            1000059007 => StructureType::SparseImageFormatProperties2,
            1000059008 => StructureType::PhysicalDeviceSparseImageFormatInfo2,
            1000117000 => StructureType::PhysicalDevicePointClippingProperties,
            1000117001 => StructureType::RenderPassInputAttachmentAspectCreateInfo,
            1000117002 => StructureType::ImageViewUsageCreateInfo,
            1000117003 => StructureType::PipelineTessellationDomainOriginStateCreateInfo,
            1000053000 => StructureType::RenderPassMultiviewCreateInfo,
            1000053001 => StructureType::PhysicalDeviceMultiviewFeatures,
            1000053002 => StructureType::PhysicalDeviceMultiviewProperties,
            1000120000 => StructureType::PhysicalDeviceVariablePointersFeatures,
            1000145000 => StructureType::ProtectedSubmitInfo,
            1000145001 => StructureType::PhysicalDeviceProtectedMemoryFeatures,
            1000145002 => StructureType::PhysicalDeviceProtectedMemoryProperties,
            1000145003 => StructureType::DeviceQueueInfo2,
            1000156000 => StructureType::SamplerYcbcrConversionCreateInfo,
            1000156001 => StructureType::SamplerYcbcrConversionInfo,
            1000156002 => StructureType::BindImagePlaneMemoryInfo,
            1000156003 => StructureType::ImagePlaneMemoryRequirementsInfo,
            1000156004 => StructureType::PhysicalDeviceSamplerYcbcrConversionFeatures,
            1000156005 => StructureType::SamplerYcbcrConversionImageFormatProperties,
            1000085000 => StructureType::DescriptorUpdateTemplateCreateInfo,
            1000071000 => StructureType::PhysicalDeviceExternalImageFormatInfo,
            1000071001 => StructureType::ExternalImageFormatProperties,
            1000071002 => StructureType::PhysicalDeviceExternalBufferInfo,
            1000071003 => StructureType::ExternalBufferProperties,
            1000071004 => StructureType::PhysicalDeviceIdProperties,
            1000072000 => StructureType::ExternalMemoryBufferCreateInfo,
            1000072001 => StructureType::ExternalMemoryImageCreateInfo,
            1000072002 => StructureType::ExportMemoryAllocateInfo,
            1000112000 => StructureType::PhysicalDeviceExternalFenceInfo,
            1000112001 => StructureType::ExternalFenceProperties,
            1000113000 => StructureType::ExportFenceCreateInfo,
            1000077000 => StructureType::ExportSemaphoreCreateInfo,
            1000076000 => StructureType::PhysicalDeviceExternalSemaphoreInfo,
            1000076001 => StructureType::ExternalSemaphoreProperties,
            1000168000 => StructureType::PhysicalDeviceMaintenance3Properties,
            1000168001 => StructureType::DescriptorSetLayoutSupport,
            1000063000 => StructureType::PhysicalDeviceShaderDrawParametersFeatures,
            49 => StructureType::PhysicalDeviceVulkan11Features,
            50 => StructureType::PhysicalDeviceVulkan11Properties,
            51 => StructureType::PhysicalDeviceVulkan12Features,
            52 => StructureType::PhysicalDeviceVulkan12Properties,
            1000147000 => StructureType::ImageFormatListCreateInfo,
            1000109000 => StructureType::AttachmentDescription2,
            1000109001 => StructureType::AttachmentReference2,
            1000109002 => StructureType::SubpassDescription2,
            1000109003 => StructureType::SubpassDependency2,
            1000109004 => StructureType::RenderPassCreateInfo2,
            1000109005 => StructureType::SubpassBeginInfo,
            1000109006 => StructureType::SubpassEndInfo,
            1000177000 => StructureType::PhysicalDevice8BitStorageFeatures,
            1000196000 => StructureType::PhysicalDeviceDriverProperties,
            1000180000 => StructureType::PhysicalDeviceShaderAtomicInt64Features,
            1000082000 => StructureType::PhysicalDeviceShaderFloat16Int8Features,
            1000197000 => StructureType::PhysicalDeviceFloatControlsProperties,
            1000161000 => StructureType::DescriptorSetLayoutBindingFlagsCreateInfo,
            1000161001 => StructureType::PhysicalDeviceDescriptorIndexingFeatures,
            1000161002 => StructureType::PhysicalDeviceDescriptorIndexingProperties,
            1000161003 => StructureType::DescriptorSetVariableDescriptorCountAllocateInfo,
            1000161004 => StructureType::DescriptorSetVariableDescriptorCountLayoutSupport,
            1000199000 => StructureType::PhysicalDeviceDepthStencilResolveProperties,
            1000199001 => StructureType::SubpassDescriptionDepthStencilResolve,
            1000221000 => StructureType::PhysicalDeviceScalarBlockLayoutFeatures,
            1000246000 => StructureType::ImageStencilUsageCreateInfo,
            1000130000 => StructureType::PhysicalDeviceSamplerFilterMinmaxProperties,
            1000130001 => StructureType::SamplerReductionModeCreateInfo,
            1000211000 => StructureType::PhysicalDeviceVulkanMemoryModelFeatures,
            1000108000 => StructureType::PhysicalDeviceImagelessFramebufferFeatures,
            1000108001 => StructureType::FramebufferAttachmentsCreateInfo,
            1000108002 => StructureType::FramebufferAttachmentImageInfo,
            1000108003 => StructureType::RenderPassAttachmentBeginInfo,
            1000253000 => StructureType::PhysicalDeviceUniformBufferStandardLayoutFeatures,
            1000175000 => StructureType::PhysicalDeviceShaderSubgroupExtendedTypesFeatures,
            1000241000 => StructureType::PhysicalDeviceSeparateDepthStencilLayoutsFeatures,
            1000241001 => StructureType::AttachmentReferenceStencilLayout,
            1000241002 => StructureType::AttachmentDescriptionStencilLayout,
            1000261000 => StructureType::PhysicalDeviceHostQueryResetFeatures,
            1000207000 => StructureType::PhysicalDeviceTimelineSemaphoreFeatures,
            1000207001 => StructureType::PhysicalDeviceTimelineSemaphoreProperties,
            1000207002 => StructureType::SemaphoreTypeCreateInfo,
            1000207003 => StructureType::TimelineSemaphoreSubmitInfo,
            1000207004 => StructureType::SemaphoreWaitInfo,
            1000207005 => StructureType::SemaphoreSignalInfo,
            1000257000 => StructureType::PhysicalDeviceBufferDeviceAddressFeatures,
            1000244001 => StructureType::BufferDeviceAddressInfo,
            1000257002 => StructureType::BufferOpaqueCaptureAddressCreateInfo,
            1000257003 => StructureType::MemoryOpaqueCaptureAddressAllocateInfo,
            1000257004 => StructureType::DeviceMemoryOpaqueCaptureAddressInfo,
            53 => StructureType::PhysicalDeviceVulkan13Features,
            54 => StructureType::PhysicalDeviceVulkan13Properties,
            1000192000 => StructureType::PipelineCreationFeedbackCreateInfo,
            1000215000 => StructureType::PhysicalDeviceShaderTerminateInvocationFeatures,
            1000245000 => StructureType::PhysicalDeviceToolProperties,
            1000276000 => StructureType::PhysicalDeviceShaderDemoteToHelperInvocationFeatures,
            1000295000 => StructureType::PhysicalDevicePrivateDataFeatures,
            1000295001 => StructureType::DevicePrivateDataCreateInfo,
            1000295002 => StructureType::PrivateDataSlotCreateInfo,
            1000297000 => StructureType::PhysicalDevicePipelineCreationCacheControlFeatures,
            1000314000 => StructureType::MemoryBarrier2,
            1000314001 => StructureType::BufferMemoryBarrier2,
            1000314002 => StructureType::ImageMemoryBarrier2,
            1000314003 => StructureType::DependencyInfo,
            1000314004 => StructureType::SubmitInfo2,
            1000314005 => StructureType::SemaphoreSubmitInfo,
            1000314006 => StructureType::CommandBufferSubmitInfo,
            1000314007 => StructureType::PhysicalDeviceSynchronization2Features,
            1000325000 => StructureType::PhysicalDeviceZeroInitializeWorkgroupMemoryFeatures,
            1000335000 => StructureType::PhysicalDeviceImageRobustnessFeatures,
            1000337000 => StructureType::CopyBufferInfo2,
            1000337001 => StructureType::CopyImageInfo2,
            1000337002 => StructureType::CopyBufferToImageInfo2,
            1000337003 => StructureType::CopyImageToBufferInfo2,
            1000337004 => StructureType::BlitImageInfo2,
            1000337005 => StructureType::ResolveImageInfo2,
            1000337006 => StructureType::BufferCopy2,
            1000337007 => StructureType::ImageCopy2,
            1000337008 => StructureType::ImageBlit2,
            1000337009 => StructureType::BufferImageCopy2,
            1000337010 => StructureType::ImageResolve2,
            1000225000 => StructureType::PhysicalDeviceSubgroupSizeControlProperties,
            1000225001 => StructureType::PipelineShaderStageRequiredSubgroupSizeCreateInfo,
            1000225002 => StructureType::PhysicalDeviceSubgroupSizeControlFeatures,
            1000138000 => StructureType::PhysicalDeviceInlineUniformBlockFeatures,
            1000138001 => StructureType::PhysicalDeviceInlineUniformBlockProperties,
            1000138002 => StructureType::WriteDescriptorSetInlineUniformBlock,
            1000138003 => StructureType::DescriptorPoolInlineUniformBlockCreateInfo,
            1000066000 => StructureType::PhysicalDeviceTextureCompressionAstcHdrFeatures,
            1000044000 => StructureType::RenderingInfo,
            1000044001 => StructureType::RenderingAttachmentInfo,
            1000044002 => StructureType::PipelineRenderingCreateInfo,
            1000044003 => StructureType::PhysicalDeviceDynamicRenderingFeatures,
            1000044004 => StructureType::CommandBufferInheritanceRenderingInfo,
            1000280000 => StructureType::PhysicalDeviceShaderIntegerDotProductFeatures,
            1000280001 => StructureType::PhysicalDeviceShaderIntegerDotProductProperties,
            1000281001 => StructureType::PhysicalDeviceTexelBufferAlignmentProperties,
            1000360000 => StructureType::FormatProperties3,
            1000413000 => StructureType::PhysicalDeviceMaintenance4Features,
            1000413001 => StructureType::PhysicalDeviceMaintenance4Properties,
            1000413002 => StructureType::DeviceBufferMemoryRequirements,
            1000413003 => StructureType::DeviceImageMemoryRequirements,
            1000001000 => StructureType::SwapchainCreateInfoKhr,
            1000001001 => StructureType::PresentInfoKhr,
            1000060007 => StructureType::DeviceGroupPresentCapabilitiesKhr,
            1000060008 => StructureType::ImageSwapchainCreateInfoKhr,
            1000060009 => StructureType::BindImageMemorySwapchainInfoKhr,
            1000060010 => StructureType::AcquireNextImageInfoKhr,
            1000060011 => StructureType::DeviceGroupPresentInfoKhr,
            1000060012 => StructureType::DeviceGroupSwapchainCreateInfoKhr,
            1000002000 => StructureType::DisplayModeCreateInfoKhr,
            1000002001 => StructureType::DisplaySurfaceCreateInfoKhr,
            1000003000 => StructureType::DisplayPresentInfoKhr,
            1000004000 => StructureType::XlibSurfaceCreateInfoKhr,
            1000005000 => StructureType::XcbSurfaceCreateInfoKhr,
            1000006000 => StructureType::WaylandSurfaceCreateInfoKhr,
            1000008000 => StructureType::AndroidSurfaceCreateInfoKhr,
            1000009000 => StructureType::Win32SurfaceCreateInfoKhr,
            1000011000 => StructureType::DebugReportCallbackCreateInfoExt,
            1000018000 => StructureType::PipelineRasterizationStateRasterizationOrderAmd,
            1000022000 => StructureType::DebugMarkerObjectNameInfoExt,
            1000022001 => StructureType::DebugMarkerObjectTagInfoExt,
            1000022002 => StructureType::DebugMarkerMarkerInfoExt,
            1000023000 => StructureType::VkEnableBetaExtensionsvideoProfileKhr,
            1000023001 => StructureType::VkEnableBetaExtensionsvideoCapabilitiesKhr,
            1000023002 => StructureType::VkEnableBetaExtensionsvideoPictureResourceKhr,
            1000023003 => StructureType::VkEnableBetaExtensionsvideoGetMemoryPropertiesKhr,
            1000023004 => StructureType::VkEnableBetaExtensionsvideoBindMemoryKhr,
            1000023005 => StructureType::VkEnableBetaExtensionsvideoSessionCreateInfoKhr,
            1000023006 => StructureType::VkEnableBetaExtensionsvideoSessionParametersCreateInfoKhr,
            1000023007 => StructureType::VkEnableBetaExtensionsvideoSessionParametersUpdateInfoKhr,
            1000023008 => StructureType::VkEnableBetaExtensionsvideoBeginCodingInfoKhr,
            1000023009 => StructureType::VkEnableBetaExtensionsvideoEndCodingInfoKhr,
            1000023010 => StructureType::VkEnableBetaExtensionsvideoCodingControlInfoKhr,
            1000023011 => StructureType::VkEnableBetaExtensionsvideoReferenceSlotKhr,
            1000023012 => StructureType::VkEnableBetaExtensionsvideoQueueFamilyProperties2Khr,
            1000023013 => StructureType::VkEnableBetaExtensionsvideoProfilesKhr,
            1000023014 => StructureType::VkEnableBetaExtensionsphysicalDeviceVideoFormatInfoKhr,
            1000023015 => StructureType::VkEnableBetaExtensionsvideoFormatPropertiesKhr,
            1000023016 => {
                StructureType::VkEnableBetaExtensionsqueueFamilyQueryResultStatusProperties2Khr
            }
            1000024000 => StructureType::VkEnableBetaExtensionsvideoDecodeInfoKhr,
            1000024001 => StructureType::VkEnableBetaExtensionsvideoDecodeCapabilitiesKhr,
            1000026000 => StructureType::DedicatedAllocationImageCreateInfoNv,
            1000026001 => StructureType::DedicatedAllocationBufferCreateInfoNv,
            1000026002 => StructureType::DedicatedAllocationMemoryAllocateInfoNv,
            1000028000 => StructureType::PhysicalDeviceTransformFeedbackFeaturesExt,
            1000028001 => StructureType::PhysicalDeviceTransformFeedbackPropertiesExt,
            1000028002 => StructureType::PipelineRasterizationStateStreamCreateInfoExt,
            1000029000 => StructureType::CuModuleCreateInfoNvx,
            1000029001 => StructureType::CuFunctionCreateInfoNvx,
            1000029002 => StructureType::CuLaunchInfoNvx,
            1000030000 => StructureType::ImageViewHandleInfoNvx,
            1000030001 => StructureType::ImageViewAddressPropertiesNvx,
            1000038000 => StructureType::VkEnableBetaExtensionsvideoEncodeH264CapabilitiesExt,
            1000038001 => {
                StructureType::VkEnableBetaExtensionsvideoEncodeH264SessionParametersCreateInfoExt
            }
            1000038002 => {
                StructureType::VkEnableBetaExtensionsvideoEncodeH264SessionParametersAddInfoExt
            }
            1000038003 => StructureType::VkEnableBetaExtensionsvideoEncodeH264VclFrameInfoExt,
            1000038004 => StructureType::VkEnableBetaExtensionsvideoEncodeH264DpbSlotInfoExt,
            1000038005 => StructureType::VkEnableBetaExtensionsvideoEncodeH264NaluSliceExt,
            1000038006 => {
                StructureType::VkEnableBetaExtensionsvideoEncodeH264EmitPictureParametersExt
            }
            1000038007 => StructureType::VkEnableBetaExtensionsvideoEncodeH264ProfileExt,
            1000038008 => StructureType::VkEnableBetaExtensionsvideoEncodeH264RateControlInfoExt,
            1000038009 => {
                StructureType::VkEnableBetaExtensionsvideoEncodeH264RateControlLayerInfoExt
            }
            1000038010 => StructureType::VkEnableBetaExtensionsvideoEncodeH264ReferenceListsExt,
            1000039000 => StructureType::VkEnableBetaExtensionsvideoEncodeH265CapabilitiesExt,
            1000039001 => {
                StructureType::VkEnableBetaExtensionsvideoEncodeH265SessionParametersCreateInfoExt
            }
            1000039002 => {
                StructureType::VkEnableBetaExtensionsvideoEncodeH265SessionParametersAddInfoExt
            }
            1000039003 => StructureType::VkEnableBetaExtensionsvideoEncodeH265VclFrameInfoExt,
            1000039004 => StructureType::VkEnableBetaExtensionsvideoEncodeH265DpbSlotInfoExt,
            1000039005 => StructureType::VkEnableBetaExtensionsvideoEncodeH265NaluSliceSegmentExt,
            1000039006 => {
                StructureType::VkEnableBetaExtensionsvideoEncodeH265EmitPictureParametersExt
            }
            1000039007 => StructureType::VkEnableBetaExtensionsvideoEncodeH265ProfileExt,
            1000039008 => StructureType::VkEnableBetaExtensionsvideoEncodeH265ReferenceListsExt,
            1000039009 => StructureType::VkEnableBetaExtensionsvideoEncodeH265RateControlInfoExt,
            1000039010 => {
                StructureType::VkEnableBetaExtensionsvideoEncodeH265RateControlLayerInfoExt
            }
            1000040000 => StructureType::VkEnableBetaExtensionsvideoDecodeH264CapabilitiesExt,
            1000040001 => StructureType::VkEnableBetaExtensionsvideoDecodeH264PictureInfoExt,
            1000040002 => StructureType::VkEnableBetaExtensionsvideoDecodeH264MvcExt,
            1000040003 => StructureType::VkEnableBetaExtensionsvideoDecodeH264ProfileExt,
            1000040004 => {
                StructureType::VkEnableBetaExtensionsvideoDecodeH264SessionParametersCreateInfoExt
            }
            1000040005 => {
                StructureType::VkEnableBetaExtensionsvideoDecodeH264SessionParametersAddInfoExt
            }
            1000040006 => StructureType::VkEnableBetaExtensionsvideoDecodeH264DpbSlotInfoExt,
            1000041000 => StructureType::TextureLodGatherFormatPropertiesAmd,
            1000044006 => StructureType::RenderingFragmentShadingRateAttachmentInfoKhr,
            1000044007 => StructureType::RenderingFragmentDensityMapAttachmentInfoExt,
            1000044008 => StructureType::AttachmentSampleCountInfoAmd,
            1000044009 => StructureType::MultiviewPerViewAttributesInfoNvx,
            1000049000 => StructureType::StreamDescriptorSurfaceCreateInfoGgp,
            1000050000 => StructureType::PhysicalDeviceCornerSampledImageFeaturesNv,
            1000056000 => StructureType::ExternalMemoryImageCreateInfoNv,
            1000056001 => StructureType::ExportMemoryAllocateInfoNv,
            1000057000 => StructureType::ImportMemoryWin32HandleInfoNv,
            1000057001 => StructureType::ExportMemoryWin32HandleInfoNv,
            1000058000 => StructureType::Win32KeyedMutexAcquireReleaseInfoNv,
            1000061000 => StructureType::ValidationFlagsExt,
            1000062000 => StructureType::ViSurfaceCreateInfoNn,
            1000067000 => StructureType::ImageViewAstcDecodeModeExt,
            1000067001 => StructureType::PhysicalDeviceAstcDecodeFeaturesExt,
            1000073000 => StructureType::ImportMemoryWin32HandleInfoKhr,
            1000073001 => StructureType::ExportMemoryWin32HandleInfoKhr,
            1000073002 => StructureType::MemoryWin32HandlePropertiesKhr,
            1000073003 => StructureType::MemoryGetWin32HandleInfoKhr,
            1000074000 => StructureType::ImportMemoryFdInfoKhr,
            1000074001 => StructureType::MemoryFdPropertiesKhr,
            1000074002 => StructureType::MemoryGetFdInfoKhr,
            1000075000 => StructureType::Win32KeyedMutexAcquireReleaseInfoKhr,
            1000078000 => StructureType::ImportSemaphoreWin32HandleInfoKhr,
            1000078001 => StructureType::ExportSemaphoreWin32HandleInfoKhr,
            1000078002 => StructureType::D3D12FenceSubmitInfoKhr,
            1000078003 => StructureType::SemaphoreGetWin32HandleInfoKhr,
            1000079000 => StructureType::ImportSemaphoreFdInfoKhr,
            1000079001 => StructureType::SemaphoreGetFdInfoKhr,
            1000080000 => StructureType::PhysicalDevicePushDescriptorPropertiesKhr,
            1000081000 => StructureType::CommandBufferInheritanceConditionalRenderingInfoExt,
            1000081001 => StructureType::PhysicalDeviceConditionalRenderingFeaturesExt,
            1000081002 => StructureType::ConditionalRenderingBeginInfoExt,
            1000084000 => StructureType::PresentRegionsKhr,
            1000087000 => StructureType::PipelineViewportWScalingStateCreateInfoNv,
            1000090000 => StructureType::SurfaceCapabilities2Ext,
            1000091000 => StructureType::DisplayPowerInfoExt,
            1000091001 => StructureType::DeviceEventInfoExt,
            1000091002 => StructureType::DisplayEventInfoExt,
            1000091003 => StructureType::SwapchainCounterCreateInfoExt,
            1000092000 => StructureType::PresentTimesInfoGoogle,
            1000097000 => StructureType::PhysicalDeviceMultiviewPerViewAttributesPropertiesNvx,
            1000098000 => StructureType::PipelineViewportSwizzleStateCreateInfoNv,
            1000099000 => StructureType::PhysicalDeviceDiscardRectanglePropertiesExt,
            1000099001 => StructureType::PipelineDiscardRectangleStateCreateInfoExt,
            1000101000 => StructureType::PhysicalDeviceConservativeRasterizationPropertiesExt,
            1000101001 => StructureType::PipelineRasterizationConservativeStateCreateInfoExt,
            1000102000 => StructureType::PhysicalDeviceDepthClipEnableFeaturesExt,
            1000102001 => StructureType::PipelineRasterizationDepthClipStateCreateInfoExt,
            1000105000 => StructureType::HdrMetadataExt,
            1000111000 => StructureType::SharedPresentSurfaceCapabilitiesKhr,
            1000114000 => StructureType::ImportFenceWin32HandleInfoKhr,
            1000114001 => StructureType::ExportFenceWin32HandleInfoKhr,
            1000114002 => StructureType::FenceGetWin32HandleInfoKhr,
            1000115000 => StructureType::ImportFenceFdInfoKhr,
            1000115001 => StructureType::FenceGetFdInfoKhr,
            1000116000 => StructureType::PhysicalDevicePerformanceQueryFeaturesKhr,
            1000116001 => StructureType::PhysicalDevicePerformanceQueryPropertiesKhr,
            1000116002 => StructureType::QueryPoolPerformanceCreateInfoKhr,
            1000116003 => StructureType::PerformanceQuerySubmitInfoKhr,
            1000116004 => StructureType::AcquireProfilingLockInfoKhr,
            1000116005 => StructureType::PerformanceCounterKhr,
            1000116006 => StructureType::PerformanceCounterDescriptionKhr,
            1000119000 => StructureType::PhysicalDeviceSurfaceInfo2Khr,
            1000119001 => StructureType::SurfaceCapabilities2Khr,
            1000119002 => StructureType::SurfaceFormat2Khr,
            1000121000 => StructureType::DisplayProperties2Khr,
            1000121001 => StructureType::DisplayPlaneProperties2Khr,
            1000121002 => StructureType::DisplayModeProperties2Khr,
            1000121003 => StructureType::DisplayPlaneInfo2Khr,
            1000121004 => StructureType::DisplayPlaneCapabilities2Khr,
            1000122000 => StructureType::IosSurfaceCreateInfoMvk,
            1000123000 => StructureType::MacosSurfaceCreateInfoMvk,
            1000128000 => StructureType::DebugUtilsObjectNameInfoExt,
            1000128001 => StructureType::DebugUtilsObjectTagInfoExt,
            1000128002 => StructureType::DebugUtilsLabelExt,
            1000128003 => StructureType::DebugUtilsMessengerCallbackDataExt,
            1000128004 => StructureType::DebugUtilsMessengerCreateInfoExt,
            1000129000 => StructureType::AndroidHardwareBufferUsageAndroid,
            1000129001 => StructureType::AndroidHardwareBufferPropertiesAndroid,
            1000129002 => StructureType::AndroidHardwareBufferFormatPropertiesAndroid,
            1000129003 => StructureType::ImportAndroidHardwareBufferInfoAndroid,
            1000129004 => StructureType::MemoryGetAndroidHardwareBufferInfoAndroid,
            1000129005 => StructureType::ExternalFormatAndroid,
            1000129006 => StructureType::AndroidHardwareBufferFormatProperties2Android,
            1000143000 => StructureType::SampleLocationsInfoExt,
            1000143001 => StructureType::RenderPassSampleLocationsBeginInfoExt,
            1000143002 => StructureType::PipelineSampleLocationsStateCreateInfoExt,
            1000143003 => StructureType::PhysicalDeviceSampleLocationsPropertiesExt,
            1000143004 => StructureType::MultisamplePropertiesExt,
            1000148000 => StructureType::PhysicalDeviceBlendOperationAdvancedFeaturesExt,
            1000148001 => StructureType::PhysicalDeviceBlendOperationAdvancedPropertiesExt,
            1000148002 => StructureType::PipelineColorBlendAdvancedStateCreateInfoExt,
            1000149000 => StructureType::PipelineCoverageToColorStateCreateInfoNv,
            1000150007 => StructureType::WriteDescriptorSetAccelerationStructureKhr,
            1000150000 => StructureType::AccelerationStructureBuildGeometryInfoKhr,
            1000150002 => StructureType::AccelerationStructureDeviceAddressInfoKhr,
            1000150003 => StructureType::AccelerationStructureGeometryAabbsDataKhr,
            1000150004 => StructureType::AccelerationStructureGeometryInstancesDataKhr,
            1000150005 => StructureType::AccelerationStructureGeometryTrianglesDataKhr,
            1000150006 => StructureType::AccelerationStructureGeometryKhr,
            1000150009 => StructureType::AccelerationStructureVersionInfoKhr,
            1000150010 => StructureType::CopyAccelerationStructureInfoKhr,
            1000150011 => StructureType::CopyAccelerationStructureToMemoryInfoKhr,
            1000150012 => StructureType::CopyMemoryToAccelerationStructureInfoKhr,
            1000150013 => StructureType::PhysicalDeviceAccelerationStructureFeaturesKhr,
            1000150014 => StructureType::PhysicalDeviceAccelerationStructurePropertiesKhr,
            1000150017 => StructureType::AccelerationStructureCreateInfoKhr,
            1000150020 => StructureType::AccelerationStructureBuildSizesInfoKhr,
            1000347000 => StructureType::PhysicalDeviceRayTracingPipelineFeaturesKhr,
            1000347001 => StructureType::PhysicalDeviceRayTracingPipelinePropertiesKhr,
            1000150015 => StructureType::RayTracingPipelineCreateInfoKhr,
            1000150016 => StructureType::RayTracingShaderGroupCreateInfoKhr,
            1000150018 => StructureType::RayTracingPipelineInterfaceCreateInfoKhr,
            1000348013 => StructureType::PhysicalDeviceRayQueryFeaturesKhr,
            1000152000 => StructureType::PipelineCoverageModulationStateCreateInfoNv,
            1000154000 => StructureType::PhysicalDeviceShaderSmBuiltinsFeaturesNv,
            1000154001 => StructureType::PhysicalDeviceShaderSmBuiltinsPropertiesNv,
            1000158000 => StructureType::DrmFormatModifierPropertiesListExt,
            1000158002 => StructureType::PhysicalDeviceImageDrmFormatModifierInfoExt,
            1000158003 => StructureType::ImageDrmFormatModifierListCreateInfoExt,
            1000158004 => StructureType::ImageDrmFormatModifierExplicitCreateInfoExt,
            1000158005 => StructureType::ImageDrmFormatModifierPropertiesExt,
            1000158006 => StructureType::DrmFormatModifierPropertiesList2Ext,
            1000160000 => StructureType::ValidationCacheCreateInfoExt,
            1000160001 => StructureType::ShaderModuleValidationCacheCreateInfoExt,
            1000163000 => {
                StructureType::VkEnableBetaExtensionsphysicalDevicePortabilitySubsetFeaturesKhr
            }
            1000163001 => {
                StructureType::VkEnableBetaExtensionsphysicalDevicePortabilitySubsetPropertiesKhr
            }
            1000164000 => StructureType::PipelineViewportShadingRateImageStateCreateInfoNv,
            1000164001 => StructureType::PhysicalDeviceShadingRateImageFeaturesNv,
            1000164002 => StructureType::PhysicalDeviceShadingRateImagePropertiesNv,
            1000164005 => StructureType::PipelineViewportCoarseSampleOrderStateCreateInfoNv,
            1000165000 => StructureType::RayTracingPipelineCreateInfoNv,
            1000165001 => StructureType::AccelerationStructureCreateInfoNv,
            1000165003 => StructureType::GeometryNv,
            1000165004 => StructureType::GeometryTrianglesNv,
            1000165005 => StructureType::GeometryAabbNv,
            1000165006 => StructureType::BindAccelerationStructureMemoryInfoNv,
            1000165007 => StructureType::WriteDescriptorSetAccelerationStructureNv,
            1000165008 => StructureType::AccelerationStructureMemoryRequirementsInfoNv,
            1000165009 => StructureType::PhysicalDeviceRayTracingPropertiesNv,
            1000165011 => StructureType::RayTracingShaderGroupCreateInfoNv,
            1000165012 => StructureType::AccelerationStructureInfoNv,
            1000166000 => StructureType::PhysicalDeviceRepresentativeFragmentTestFeaturesNv,
            1000166001 => StructureType::PipelineRepresentativeFragmentTestStateCreateInfoNv,
            1000170000 => StructureType::PhysicalDeviceImageViewImageFormatInfoExt,
            1000170001 => StructureType::FilterCubicImageViewImageFormatPropertiesExt,
            1000178000 => StructureType::ImportMemoryHostPointerInfoExt,
            1000178001 => StructureType::MemoryHostPointerPropertiesExt,
            1000178002 => StructureType::PhysicalDeviceExternalMemoryHostPropertiesExt,
            1000181000 => StructureType::PhysicalDeviceShaderClockFeaturesKhr,
            1000183000 => StructureType::PipelineCompilerControlCreateInfoAmd,
            1000184000 => StructureType::CalibratedTimestampInfoExt,
            1000185000 => StructureType::PhysicalDeviceShaderCorePropertiesAmd,
            1000187000 => StructureType::VkEnableBetaExtensionsvideoDecodeH265CapabilitiesExt,
            1000187001 => {
                StructureType::VkEnableBetaExtensionsvideoDecodeH265SessionParametersCreateInfoExt
            }
            1000187002 => {
                StructureType::VkEnableBetaExtensionsvideoDecodeH265SessionParametersAddInfoExt
            }
            1000187003 => StructureType::VkEnableBetaExtensionsvideoDecodeH265ProfileExt,
            1000187004 => StructureType::VkEnableBetaExtensionsvideoDecodeH265PictureInfoExt,
            1000187005 => StructureType::VkEnableBetaExtensionsvideoDecodeH265DpbSlotInfoExt,
            1000174000 => StructureType::DeviceQueueGlobalPriorityCreateInfoKhr,
            1000388000 => StructureType::PhysicalDeviceGlobalPriorityQueryFeaturesKhr,
            1000388001 => StructureType::QueueFamilyGlobalPriorityPropertiesKhr,
            1000189000 => StructureType::DeviceMemoryOverallocationCreateInfoAmd,
            1000190000 => StructureType::PhysicalDeviceVertexAttributeDivisorPropertiesExt,
            1000190001 => StructureType::PipelineVertexInputDivisorStateCreateInfoExt,
            1000190002 => StructureType::PhysicalDeviceVertexAttributeDivisorFeaturesExt,
            1000191000 => StructureType::PresentFrameTokenGgp,
            1000201000 => StructureType::PhysicalDeviceComputeShaderDerivativesFeaturesNv,
            1000202000 => StructureType::PhysicalDeviceMeshShaderFeaturesNv,
            1000202001 => StructureType::PhysicalDeviceMeshShaderPropertiesNv,
            1000203000 => StructureType::PhysicalDeviceFragmentShaderBarycentricFeaturesNv,
            1000204000 => StructureType::PhysicalDeviceShaderImageFootprintFeaturesNv,
            1000205000 => StructureType::PipelineViewportExclusiveScissorStateCreateInfoNv,
            1000205002 => StructureType::PhysicalDeviceExclusiveScissorFeaturesNv,
            1000206000 => StructureType::CheckpointDataNv,
            1000206001 => StructureType::QueueFamilyCheckpointPropertiesNv,
            1000209000 => StructureType::PhysicalDeviceShaderIntegerFunctions2FeaturesIntel,
            1000210000 => StructureType::QueryPoolPerformanceQueryCreateInfoIntel,
            1000210001 => StructureType::InitializePerformanceApiInfoIntel,
            1000210002 => StructureType::PerformanceMarkerInfoIntel,
            1000210003 => StructureType::PerformanceStreamMarkerInfoIntel,
            1000210004 => StructureType::PerformanceOverrideInfoIntel,
            1000210005 => StructureType::PerformanceConfigurationAcquireInfoIntel,
            1000212000 => StructureType::PhysicalDevicePciBusInfoPropertiesExt,
            1000213000 => StructureType::DisplayNativeHdrSurfaceCapabilitiesAmd,
            1000213001 => StructureType::SwapchainDisplayNativeHdrCreateInfoAmd,
            1000214000 => StructureType::ImagepipeSurfaceCreateInfoFuchsia,
            1000217000 => StructureType::MetalSurfaceCreateInfoExt,
            1000218000 => StructureType::PhysicalDeviceFragmentDensityMapFeaturesExt,
            1000218001 => StructureType::PhysicalDeviceFragmentDensityMapPropertiesExt,
            1000218002 => StructureType::RenderPassFragmentDensityMapCreateInfoExt,
            1000226000 => StructureType::FragmentShadingRateAttachmentInfoKhr,
            1000226001 => StructureType::PipelineFragmentShadingRateStateCreateInfoKhr,
            1000226002 => StructureType::PhysicalDeviceFragmentShadingRatePropertiesKhr,
            1000226003 => StructureType::PhysicalDeviceFragmentShadingRateFeaturesKhr,
            1000226004 => StructureType::PhysicalDeviceFragmentShadingRateKhr,
            1000227000 => StructureType::PhysicalDeviceShaderCoreProperties2Amd,
            1000229000 => StructureType::PhysicalDeviceCoherentMemoryFeaturesAmd,
            1000234000 => StructureType::PhysicalDeviceShaderImageAtomicInt64FeaturesExt,
            1000237000 => StructureType::PhysicalDeviceMemoryBudgetPropertiesExt,
            1000238000 => StructureType::PhysicalDeviceMemoryPriorityFeaturesExt,
            1000238001 => StructureType::MemoryPriorityAllocateInfoExt,
            1000239000 => StructureType::SurfaceProtectedCapabilitiesKhr,
            1000240000 => StructureType::PhysicalDeviceDedicatedAllocationImageAliasingFeaturesNv,
            1000244000 => StructureType::PhysicalDeviceBufferDeviceAddressFeaturesExt,
            1000244002 => StructureType::BufferDeviceAddressCreateInfoExt,
            1000247000 => StructureType::ValidationFeaturesExt,
            1000248000 => StructureType::PhysicalDevicePresentWaitFeaturesKhr,
            1000249000 => StructureType::PhysicalDeviceCooperativeMatrixFeaturesNv,
            1000249001 => StructureType::CooperativeMatrixPropertiesNv,
            1000249002 => StructureType::PhysicalDeviceCooperativeMatrixPropertiesNv,
            1000250000 => StructureType::PhysicalDeviceCoverageReductionModeFeaturesNv,
            1000250001 => StructureType::PipelineCoverageReductionStateCreateInfoNv,
            1000250002 => StructureType::FramebufferMixedSamplesCombinationNv,
            1000251000 => StructureType::PhysicalDeviceFragmentShaderInterlockFeaturesExt,
            1000252000 => StructureType::PhysicalDeviceYcbcrImageArraysFeaturesExt,
            1000254000 => StructureType::PhysicalDeviceProvokingVertexFeaturesExt,
            1000254001 => StructureType::PipelineRasterizationProvokingVertexStateCreateInfoExt,
            1000254002 => StructureType::PhysicalDeviceProvokingVertexPropertiesExt,
            1000255000 => StructureType::SurfaceFullScreenExclusiveInfoExt,
            1000255002 => StructureType::SurfaceCapabilitiesFullScreenExclusiveExt,
            1000255001 => StructureType::SurfaceFullScreenExclusiveWin32InfoExt,
            1000256000 => StructureType::HeadlessSurfaceCreateInfoExt,
            1000259000 => StructureType::PhysicalDeviceLineRasterizationFeaturesExt,
            1000259001 => StructureType::PipelineRasterizationLineStateCreateInfoExt,
            1000259002 => StructureType::PhysicalDeviceLineRasterizationPropertiesExt,
            1000260000 => StructureType::PhysicalDeviceShaderAtomicFloatFeaturesExt,
            1000265000 => StructureType::PhysicalDeviceIndexTypeUint8FeaturesExt,
            1000267000 => StructureType::PhysicalDeviceExtendedDynamicStateFeaturesExt,
            1000269000 => StructureType::PhysicalDevicePipelineExecutablePropertiesFeaturesKhr,
            1000269001 => StructureType::PipelineInfoKhr,
            1000269002 => StructureType::PipelineExecutablePropertiesKhr,
            1000269003 => StructureType::PipelineExecutableInfoKhr,
            1000269004 => StructureType::PipelineExecutableStatisticKhr,
            1000269005 => StructureType::PipelineExecutableInternalRepresentationKhr,
            1000273000 => StructureType::PhysicalDeviceShaderAtomicFloat2FeaturesExt,
            1000277000 => StructureType::PhysicalDeviceDeviceGeneratedCommandsPropertiesNv,
            1000277001 => StructureType::GraphicsShaderGroupCreateInfoNv,
            1000277002 => StructureType::GraphicsPipelineShaderGroupsCreateInfoNv,
            1000277003 => StructureType::IndirectCommandsLayoutTokenNv,
            1000277004 => StructureType::IndirectCommandsLayoutCreateInfoNv,
            1000277005 => StructureType::GeneratedCommandsInfoNv,
            1000277006 => StructureType::GeneratedCommandsMemoryRequirementsInfoNv,
            1000277007 => StructureType::PhysicalDeviceDeviceGeneratedCommandsFeaturesNv,
            1000278000 => StructureType::PhysicalDeviceInheritedViewportScissorFeaturesNv,
            1000278001 => StructureType::CommandBufferInheritanceViewportScissorInfoNv,
            1000281000 => StructureType::PhysicalDeviceTexelBufferAlignmentFeaturesExt,
            1000282000 => StructureType::CommandBufferInheritanceRenderPassTransformInfoQcom,
            1000282001 => StructureType::RenderPassTransformBeginInfoQcom,
            1000284000 => StructureType::PhysicalDeviceDeviceMemoryReportFeaturesExt,
            1000284001 => StructureType::DeviceDeviceMemoryReportCreateInfoExt,
            1000284002 => StructureType::DeviceMemoryReportCallbackDataExt,
            1000286000 => StructureType::PhysicalDeviceRobustness2FeaturesExt,
            1000286001 => StructureType::PhysicalDeviceRobustness2PropertiesExt,
            1000287000 => StructureType::SamplerCustomBorderColorCreateInfoExt,
            1000287001 => StructureType::PhysicalDeviceCustomBorderColorPropertiesExt,
            1000287002 => StructureType::PhysicalDeviceCustomBorderColorFeaturesExt,
            1000290000 => StructureType::PipelineLibraryCreateInfoKhr,
            1000294000 => StructureType::PresentIdKhr,
            1000294001 => StructureType::PhysicalDevicePresentIdFeaturesKhr,
            1000299000 => StructureType::VkEnableBetaExtensionsvideoEncodeInfoKhr,
            1000299001 => StructureType::VkEnableBetaExtensionsvideoEncodeRateControlInfoKhr,
            1000299002 => StructureType::VkEnableBetaExtensionsvideoEncodeRateControlLayerInfoKhr,
            1000299003 => StructureType::VkEnableBetaExtensionsvideoEncodeCapabilitiesKhr,
            1000300000 => StructureType::PhysicalDeviceDiagnosticsConfigFeaturesNv,
            1000300001 => StructureType::DeviceDiagnosticsConfigCreateInfoNv,
            1000314008 => StructureType::QueueFamilyCheckpointProperties2Nv,
            1000314009 => StructureType::CheckpointData2Nv,
            1000320000 => StructureType::PhysicalDeviceGraphicsPipelineLibraryFeaturesExt,
            1000320001 => StructureType::PhysicalDeviceGraphicsPipelineLibraryPropertiesExt,
            1000320002 => StructureType::GraphicsPipelineLibraryCreateInfoExt,
            1000323000 => StructureType::PhysicalDeviceShaderSubgroupUniformControlFlowFeaturesKhr,
            1000326000 => StructureType::PhysicalDeviceFragmentShadingRateEnumsPropertiesNv,
            1000326001 => StructureType::PhysicalDeviceFragmentShadingRateEnumsFeaturesNv,
            1000326002 => StructureType::PipelineFragmentShadingRateEnumStateCreateInfoNv,
            1000327000 => StructureType::AccelerationStructureGeometryMotionTrianglesDataNv,
            1000327001 => StructureType::PhysicalDeviceRayTracingMotionBlurFeaturesNv,
            1000327002 => StructureType::AccelerationStructureMotionInfoNv,
            1000330000 => StructureType::PhysicalDeviceYcbcr2Plane444FormatsFeaturesExt,
            1000332000 => StructureType::PhysicalDeviceFragmentDensityMap2FeaturesExt,
            1000332001 => StructureType::PhysicalDeviceFragmentDensityMap2PropertiesExt,
            1000333000 => StructureType::CopyCommandTransformInfoQcom,
            1000336000 => StructureType::PhysicalDeviceWorkgroupMemoryExplicitLayoutFeaturesKhr,
            1000340000 => StructureType::PhysicalDevice4444FormatsFeaturesExt,
            1000342000 => {
                StructureType::PhysicalDeviceRasterizationOrderAttachmentAccessFeaturesArm
            }
            1000344000 => StructureType::PhysicalDeviceRgba10X6FormatsFeaturesExt,
            1000346000 => StructureType::DirectfbSurfaceCreateInfoExt,
            1000351000 => StructureType::PhysicalDeviceMutableDescriptorTypeFeaturesValve,
            1000351002 => StructureType::MutableDescriptorTypeCreateInfoValve,
            1000352000 => StructureType::PhysicalDeviceVertexInputDynamicStateFeaturesExt,
            1000352001 => StructureType::VertexInputBindingDescription2Ext,
            1000352002 => StructureType::VertexInputAttributeDescription2Ext,
            1000353000 => StructureType::PhysicalDeviceDrmPropertiesExt,
            1000355000 => StructureType::PhysicalDeviceDepthClipControlFeaturesExt,
            1000355001 => StructureType::PipelineViewportDepthClipControlCreateInfoExt,
            1000356000 => StructureType::PhysicalDevicePrimitiveTopologyListRestartFeaturesExt,
            1000364000 => StructureType::ImportMemoryZirconHandleInfoFuchsia,
            1000364001 => StructureType::MemoryZirconHandlePropertiesFuchsia,
            1000364002 => StructureType::MemoryGetZirconHandleInfoFuchsia,
            1000365000 => StructureType::ImportSemaphoreZirconHandleInfoFuchsia,
            1000365001 => StructureType::SemaphoreGetZirconHandleInfoFuchsia,
            1000366000 => StructureType::BufferCollectionCreateInfoFuchsia,
            1000366001 => StructureType::ImportMemoryBufferCollectionFuchsia,
            1000366002 => StructureType::BufferCollectionImageCreateInfoFuchsia,
            1000366003 => StructureType::BufferCollectionPropertiesFuchsia,
            1000366004 => StructureType::BufferConstraintsInfoFuchsia,
            1000366005 => StructureType::BufferCollectionBufferCreateInfoFuchsia,
            1000366006 => StructureType::ImageConstraintsInfoFuchsia,
            1000366007 => StructureType::ImageFormatConstraintsInfoFuchsia,
            1000366008 => StructureType::SysmemColorSpaceFuchsia,
            1000366009 => StructureType::BufferCollectionConstraintsInfoFuchsia,
            1000369000 => StructureType::SubpassShadingPipelineCreateInfoHuawei,
            1000369001 => StructureType::PhysicalDeviceSubpassShadingFeaturesHuawei,
            1000369002 => StructureType::PhysicalDeviceSubpassShadingPropertiesHuawei,
            1000370000 => StructureType::PhysicalDeviceInvocationMaskFeaturesHuawei,
            1000371000 => StructureType::MemoryGetRemoteAddressInfoNv,
            1000371001 => StructureType::PhysicalDeviceExternalMemoryRdmaFeaturesNv,
            1000377000 => StructureType::PhysicalDeviceExtendedDynamicState2FeaturesExt,
            1000378000 => StructureType::ScreenSurfaceCreateInfoQnx,
            1000381000 => StructureType::PhysicalDeviceColorWriteEnableFeaturesExt,
            1000381001 => StructureType::PipelineColorWriteCreateInfoExt,
            1000382000 => StructureType::PhysicalDevicePrimitivesGeneratedQueryFeaturesExt,
            1000391000 => StructureType::PhysicalDeviceImageViewMinLodFeaturesExt,
            1000391001 => StructureType::ImageViewMinLodCreateInfoExt,
            1000392000 => StructureType::PhysicalDeviceMultiDrawFeaturesExt,
            1000392001 => StructureType::PhysicalDeviceMultiDrawPropertiesExt,
            1000393000 => StructureType::PhysicalDeviceImage2DViewOf3DFeaturesExt,
            1000411000 => StructureType::PhysicalDeviceBorderColorSwizzleFeaturesExt,
            1000411001 => StructureType::SamplerBorderColorComponentMappingCreateInfoExt,
            1000412000 => StructureType::PhysicalDevicePageableDeviceLocalMemoryFeaturesExt,
            1000420000 => StructureType::PhysicalDeviceDescriptorSetHostMappingFeaturesValve,
            1000420001 => StructureType::DescriptorSetBindingReferenceValve,
            1000420002 => StructureType::DescriptorSetLayoutHostMappingInfoValve,
            1000425000 => StructureType::PhysicalDeviceFragmentDensityMapOffsetFeaturesQcom,
            1000425001 => StructureType::PhysicalDeviceFragmentDensityMapOffsetPropertiesQcom,
            1000425002 => StructureType::SubpassFragmentDensityMapOffsetEndInfoQcom,
            1000430000 => StructureType::PhysicalDeviceLinearColorAttachmentFeaturesNv,
            _ => StructureType::Unknown,
        }
    }
}
